### ISSUE TITLE
Error when pushing

### ISSUE THREAD

**Issue by Scream4Life** [meg768/homebridge-pushover#2]
Hi, I installed everything and just took your example of the messages and got this message, when I push my first message

```
[2019-2-14 14:05:44] [Pushover] Sending message: Larm avaktiverat
/usr/local/lib/node_modules/homebridge-pushover/node_modules/pushover-notifications/lib/pushover.js:83
	    throw new Error(d.errors[0]);
	    ^

Error: application token is invalid
    at Pushover.errors (/usr/local/lib/node_modules/homebridge-pushover/node_modules/pushover-notifications/lib/pushover.js:83:12)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-pushover/node_modules/pushover-notifications/lib/pushover.js:167:11)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

I copied the token directly from Pushover and tried as user my mail account, with which I log into Pushover as well as the Pushover-notification email. Result is the same.

node -v is 8.11.3

**Comment by Scream4Life** [comment]
Ok, found it myself. What I inserted as token is basically the user-attribute. And I needed an App-Token separately for the token-attribute. I found some information about it here https://pushover.net/faq#licensing-paid. Now it works.
