### ISSUE TITLE
index.js path Windows 10

### ISSUE THREAD

**Issue by pax0707** [meg768/homebridge-pushover#5]
Not a proper solution but I just ended hardcoding it to my path.

```
[8/18/2019, 11:37:36 PM] Loaded plugin: homebridge-pushover
path.js:39
    throw new ERR_INVALID_ARG_TYPE('path', 'string', path);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at assertPath (path.js:39:11)
    at Object.join (path.js:432:7)
    at Plugin.module.exports [as initializer] (C:\Users\pax07\AppData\Roaming\npm\node_modules\homebridge-pushover\index.js:8:42)
```

**Comment by meg768** [comment]
Sorry. Not using Windows.
