### ISSUE TITLE
TypeError: Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by fab301s** [meg768/homebridge-pushover#9]
After updating to 1.0.11, receive error as follows.  Suggestions welcome.

```
TypeError: Cannot read property 'forEach' of undefined
    at Platform.accessories (/usr/local/lib/node_modules/homebridge-pushover/src/platform.js:63:30)
    at Server._loadPlatformAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:403:20)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:341:16)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:90:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
```

**Comment by meg768** [comment]
The "messages" section in the config file seems to be missing. Is this the case?

**Comment by fab301s** [comment]
It’s likely, thanks.  Has the format of config.json changed?

**Comment by fab301s** [comment]
That was it.  Config.json format was different.  Thanks for the pointer!
